INSERT INTO uiconfig (section, var, value, description) 
VALUES 
('adescom', 'synchronize', '1', 'Flaga określająca czy włączona jest synchronizacja'), 
('adescom', 'invoice_add_calls', '1', 'Flaga określająca czy do FV generowane są pozycje za połączenia telefoniczne'), 
('adescom', 'invoice_separate_voip_accounts', '0', 'Flaga określająca czy na FV generowane są oddzielne pozycje dla poszczególnych numerów telefonów'), 
('adescom', 'invoice_separate_fractions', '1', 'Flaga określająca czy na FV generowane są oddzielne pozycje dla poszczególnych frakcji'), 
('adescom', 'invoice_position_calls', 'Połączenia telefoniczne: %calls_fraction (%calls_count szt.) za okres od %calls_periodfrom do %calls_periodto', 'Szablon nazwy pozycji na FV za połączenia telefoniczne'), 
('adescom', 'invoice_position_subscribe', 'Abonament telefoniczny za miesiąc: %subscribe_period', 'Szablon nazwy pozycji na FV za abonament telefiniczny'), 
('adescom', 'default_clid_ported', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer przeniesiony"'), 
('adescom', 'default_clid_ctmid', '1', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Centrala CTM"'), 
('adescom', 'default_clid_registration_type', 'area+local', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Tryb rejestracji"'), 
('adescom', 'default_clid_phoneid', '11', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Profil telefonu"'), 
('adescom', 'default_clid_phone_line', '5061', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Port telefonu"'), 
('adescom', 'default_clid_displayname', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Nazwa wyświetlana"'), 
('adescom', 'default_clid_email', 'abc@abc.com', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "E-mail"'), 
('adescom', 'default_clid_context', 'All', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Grupa numeracyjna"'), 
('adescom', 'default_clid_emergency_context', 'alarm_numbers', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Grupa numeracyjna połączeń alarmowych"'), 
('adescom', 'default_clid_host', 'dynamiczny', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Adres IP"'), 
('adescom', 'default_clid_hostname', 'dynamiczny', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Nazwa hosta"'), 
('adescom', 'default_clid_mac_address', 'AAAAAAAAAAAA', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Adres MAC"'), 
('adescom', 'default_clid_serial_number', '123', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer seryjny"'), 
('adescom', 'default_clid_voicemail', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Włącz pocztę głosową"'), 
('adescom', 'default_clid_voicemailpassword', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Hasło poczty głosowej"'), 
('adescom', 'default_clid_voicemailattach', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Wysyłaj wiadomości poczty głosowej jak załącznik e-mail"'), 
('adescom', 'default_clid_tariffid', '8', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Taryfa"'), 
('adescom', 'default_clid_active', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Aktywuj"'), 
('adescom', 'default_clid_autoactivation_date', '2016/04/04', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Data aktywacji"'), 
('adescom', 'default_clid_is_prepaid', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Prepaid"'), 
('adescom', 'default_clid_prepaid_state', '100', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Stan konta [PLN]"'), 
('adescom', 'default_clid_absolute_cost_limit', '500', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Bezwzględny limit kosztów [PLN]"'), 
('adescom', 'default_clid_clip', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Prezentacja numeru (CLIP)"'), 
('adescom', 'default_clid_clir', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zastrzeż numer (CLIR)"'), 
('adescom', 'default_clid_clir_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj abonentowi na zmianę ustawień CLIR"'), 
('adescom', 'default_clid_acrej', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Odrzucanie połączeń anonimowych (ACREJ)"'), 
('adescom', 'default_clid_acrej_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj abonentowi na zmianę ustawień ACREJ"'), 
('adescom', 'default_clid_clirovr', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Przełamanie ustawień CLIR"'), 
('adescom', 'default_clid_dnd', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "DND - usługa "nie przeszkadzać""'), 
('adescom', 'default_clid_dnd_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj abonentowi na zmianę DND"'), 
('adescom', 'default_clid_hotline', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer gorącej linii"'), 
('adescom', 'default_clid_hotline_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj na gorącą linie"'), 
('adescom', 'default_clid_cw', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Połączenia oczekujące"'), 
('adescom', 'default_clid_cw_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj abonentowi na zmianę ustawień połączeń oczekujących"'), 
('adescom', 'default_clid_nway', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Połączenia trójstronne"'), 
('adescom', 'default_clid_alarm', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Włącz usługę Budzenie"'), 
('adescom', 'default_clid_forwarding', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj na przekierowania"'), 
('adescom', 'default_clid_cfu', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer przekierowań bezwarunkowych (CFU)"'), 
('adescom', 'default_clid_cfb', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer przekierowania gdy zajęty (CFB)"'), 
('adescom', 'default_clid_cfnr', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer przekierowania gdy brak odpowiedzi (CFNR)"'), 
('adescom', 'default_clid_cfur', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Numer przekierowania gdy niedostępny (CFUR)"'), 
('adescom', 'default_clid_f2m', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Włącz usługę Fax2Mail"'), 
('adescom', 'default_clid_uf2m', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Fax2Mail - Przekierowanie bezwarunkowe"'), 
('adescom', 'default_clid_nrf2m', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Fax2Mail - Przekierowanie gdy nieosiągalny"'), 
('adescom', 'default_clid_blind_xfer', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj na transfery ślepe"'), 
('adescom', 'default_clid_at_xfer', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj na transfery nadzorowane"'), 
('adescom', 'default_clid_ocb_allowed', 'true', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Zezwalaj na OCB"'), 
('adescom', 'default_clid_ocb', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Poziom OCB"'), 
('adescom', 'default_clid_ocb_password', 'abc', 'Flaga określająca na formatce dodawania konta VoIP domyślną wartość opcji "Hasło OCB"'),
('adescom', 'hide_voipaccount_login', 'false', 'Flaga określająca czy należy ukryć pole login na formatkach dodawania i edycji konta VoIP'),
('adescom', 'hide_voipaccount_status', 'false', 'Flaga określająca czy należy ukryć pole status na formatkach dodawania i edycji konta VoIP'),
('adescom', 'hide_voipaccount_location', 'false', 'Flaga określająca czy należy ukryć pole location na formatkach dodawania i edycji konta VoIP');
